[workspace]
resolver = "3"
members = [ "bevy-builder","turret-game", "voxel-map-editor"]

[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
